import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import ReactQueryClientProvider from "./ReactQueryClientProvider";
import AuthProvider from "./contexts/AuthContext";
import Navbar from "./components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryClientProvider>
        <AuthProvider>
          <body className={inter.className}>
            <Navbar />
            {children}
          </body>
        </AuthProvider>
      </ReactQueryClientProvider>
    </html>
  );
}
